version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}.mongodb.docker
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    volumes:
      - mongo.data:/data/db
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    networks:
      - global

volumes:
  mongo.data:

networks:
  global:
    external: false