version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: ${COMPOSE_PROJECT_NAME}.mongodb.docker
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_NAME}
    volumes:
      - mongo.data:/data/db
    ports:
      - 127.0.0.1:${MONGO_PORT}:27017
    networks:
      - global

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password   

  frontend:
    image: frontend
    ports:
      - 4000:4000

volumes:
  mongo.data:

networks:
  global:
    external: false