version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: travel.mongodb.docker
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: travelsDB
    volumes:
      - mongodb-data:/data/db
    ports:
      - 27018:27017

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=user
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password   
  
  frontend: 
    image: frontend
    ports: 
      - 4000:4000

volumes:
  mongodb-data:
    driver: local
  